// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Model;

public partial class Order
{
    public int IdOrder { get; set; }

    public int IdHarvest { get; set; }

    public int IdPerson { get; set; }

    public double Quantity { get; set; }

    public decimal Price { get; set; }

    public DateTime DateOfOrder { get; set; }

    public virtual Harvest IdHarvestNavigation { get; set; }

    public virtual Person IdPersonNavigation { get; set; }
}