// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Model;

public partial class Person
{
    public int IdPerson { get; set; }

    public string Name { get; set; }

    public int  PhoneNum { get; set; }

    public string Role { get; set; }

    public virtual ICollection<Contract> Contract { get; set; } = new List<Contract>();

    public virtual ICollection<Crop> Crop { get; set; } = new List<Crop>();

    public virtual ICollection<Order> Order { get; set; } = new List<Order>();

    public virtual ICollection<Plot> Plot { get; set; } = new List<Plot>();

    public virtual Workers Workers { get; set; }
}