// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Model;

public partial class PersonAddress
{
    public int IdPerson { get; set; }

    public string Place { get; set; }

    public int PostalCode { get; set; }

    public virtual Person IdPersonNavigation { get; set; }
}