// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Model;

public partial class Plot
{
    public int IdPlot { get; set; }

    public int IdPerson { get; set; }

    public int IdCrop { get; set; }

    public string CommonName { get; set; }

    public int IdSoilQuality { get; set; }

    public int IdSoilCategory { get; set; }

    public int IdInfrastructure { get; set; }

    public double Size { get; set; }

    public string Gpslocation { get; set; }

    public virtual Crop IdCropNavigation { get; set; }

    public virtual Infrastructure IdInfrastructureNavigation { get; set; }

    public virtual Person IdPersonNavigation { get; set; }

    public virtual SoilCategory IdSoilCategoryNavigation { get; set; }

    public virtual SoilQuality IdSoilQualityNavigation { get; set; }
}