// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Model;

public partial class SoilQuality
{
    public int IdSoilQuality { get; set; }

    public string Quality { get; set; }

    public virtual ICollection<Plot> Plot { get; set; } = new List<Plot>();
}