// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Model;

public partial class Species
{
    public int IdSpecies { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Crop> Crop { get; set; } = new List<Crop>();

    public virtual ICollection<Variant> Variant { get; set; } = new List<Variant>();
}