// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Model;

public partial class Status
{
    public int IdStatus { get; set; }

    public string Status1 { get; set; }

    public virtual ICollection<Crop> Crop { get; set; } = new List<Crop>();
}