// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Model;

public partial class Tasks
{
    public int IdTask { get; set; }

    public string Task1 { get; set; }

    public int IdTaskStatus { get; set; }

    public int IdPerson { get; set; }

    public virtual ICollection<Crop> Crop { get; set; } = new List<Crop>();

    public virtual Workers IdPersonNavigation { get; set; }

    public virtual TaskStatus IdTaskStatusNavigation { get; set; }
}