// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Model;

public partial class TypeContract
{
    public int IdTypeContract { get; set; }

    public string Type { get; set; }

    public virtual ICollection<Contract> Contract { get; set; } = new List<Contract>();
}