// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Model;

public partial class Variant
{
    public int IdVariant { get; set; }

    public int IdSpecies { get; set; }

    public string Name { get; set; }

    public int IdPassport { get; set; }

    public int IdSeason { get; set; }

    public virtual PlantingSeason IdSeasonNavigation { get; set; }

    public virtual Species IdSpeciesNavigation { get; set; }

    public virtual ICollection<Passport> Passport { get; set; } = new List<Passport>();

    public virtual ICollection<Recipes> Recipes { get; set; } = new List<Recipes>();

    public virtual ICollection<UseCaseInformation> UseCaseInformation { get; set; } = new List<UseCaseInformation>();
}