// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using RPPP_WebApp.ViewModels;
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Model;

public partial class Workers
{
    public int IdPerson { get; set; }

    public int IdWorkerType { get; set; }

    public double Salary { get; set; }

    public virtual ICollection<Harvest> Harvest { get; set; } = new List<Harvest>();

    public virtual Person IdPersonNavigation { get; set; }

    public virtual WorkerType IdWorkerTypeNavigation { get; set; }

    public virtual ICollection<Tasks> Task { get; set; } = new List<Tasks>();
    public IEnumerable<Task2ViewModel> ItemsW { get; set; }

}