// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Model;

public partial class WorkerType
{
    public int IdWorkerType { get; set; }

    public string Type { get; set; }

    public virtual ICollection<Workers> Workers { get; set; } = new List<Workers>();
}